// Supabase wiring: reads config.js, loads the vendored supabase-js library, and exposes
// authentication helpers plus the cloud-document adapter used by sync.js.
//
// config.js is generated by the deploy workflow from repository Variables (see config.example.js).
// When it is missing or empty the app runs in local-only mode, exactly as before.

const DOCUMENT_TABLE = 'task_manager_documents';
const AUTH_STORAGE_KEY = 'task-manager-auth';
const SUPABASE_SCRIPT = 'vendor/supabase.js';

/** Returns { url, key } or null when cloud mode is not configured. */
export async function loadCloudConfig() {
  let config;
  try {
    config = await import('../config.js');
  } catch {
    return null;
  }
  const url = typeof config.SUPABASE_URL === 'string' ? config.SUPABASE_URL.trim().replace(/\/+$/, '') : '';
  const key = typeof config.SUPABASE_ANON_KEY === 'string' ? config.SUPABASE_ANON_KEY.trim() : '';
  if (!/^https:\/\/[a-z0-9.-]+$/i.test(url) || key === '') return null;
  return { url, key };
}

function loadSupabaseLibrary() {
  if (window.supabase?.createClient) return Promise.resolve(window.supabase);
  return new Promise((resolve, reject) => {
    const script = document.createElement('script');
    script.src = SUPABASE_SCRIPT;
    script.onload = () => (window.supabase?.createClient ? resolve(window.supabase) : reject(new Error('supabase-js failed to load')));
    script.onerror = () => reject(new Error('supabase-js failed to load'));
    document.head.append(script);
  });
}

/** The app's own address - where password-reset and confirmation links return to. */
function appUrl() {
  return `${window.location.origin}${window.location.pathname}`;
}

export async function createCloud({ url, key }) {
  const library = await loadSupabaseLibrary();
  const client = library.createClient(url, key, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      storageKey: AUTH_STORAGE_KEY,
      // Implicit flow: a reset link works even when opened on another device than the one that asked for it.
      detectSessionInUrl: true,
      flowType: 'implicit',
    },
  });

  return {
    client,
    signIn: (email, password) => client.auth.signInWithPassword({ email, password }),
    signUp: (email, password) => client.auth.signUp({ email, password, options: { emailRedirectTo: appUrl() } }),
    requestPasswordReset: email => client.auth.resetPasswordForEmail(email, { redirectTo: appUrl() }),
    updatePassword: password => client.auth.updateUser({ password }),
    signOut: () => client.auth.signOut({ scope: 'local' }),
    /** callback(event, session). Supabase must not be awaited inside it, so work is deferred. */
    onAuthChange(callback) {
      const { data } = client.auth.onAuthStateChange((event, session) => {
        setTimeout(() => callback(event, session), 0);
      });
      return () => data.subscription.unsubscribe();
    },
    createRemote: userId => createDocumentRemote(client, userId),
  };
}

/**
 * One row per user: { user_id, data (the whole app state as JSON), version }.
 * Row-level security limits every query to the signed-in user; a trigger bumps the version
 * on each update (supabase/schema.sql), so an update filtered by the old version fails
 * when another device saved in between.
 */
export function createDocumentRemote(client, userId) {
  const table = () => client.from(DOCUMENT_TABLE);
  return {
    async fetch() {
      const { data, error } = await table().select('data, version').eq('user_id', userId).maybeSingle();
      if (error) throw error;
      return data ? { data: data.data, version: data.version } : null;
    },
    async insert(documentData) {
      const { data, error } = await table().insert({ user_id: userId, data: documentData }).select('version').single();
      if (error?.code === '23505') return { conflict: true }; // another device created the row first
      if (error) throw error;
      return { version: data.version };
    },
    async update(documentData, expectedVersion) {
      const { data, error } = await table()
        .update({ data: documentData })
        .eq('user_id', userId)
        .eq('version', expectedVersion)
        .select('version');
      if (error) throw error;
      return data.length > 0 ? { version: data[0].version } : { conflict: true };
    },
    /**
     * onChange(version) whenever the row changes in the cloud (realtime), and onChange(null) each time
     * the live channel (re)connects - changes made while it was not connected are then checked for.
     * Returns unsubscribe.
     */
    subscribe(onChange) {
      const channel = client
        .channel(`task-manager-${userId}`)
        .on('postgres_changes', { event: '*', schema: 'public', table: DOCUMENT_TABLE, filter: `user_id=eq.${userId}` },
          payload => onChange(payload.new?.version ?? null))
        .subscribe(channelStatus => {
          if (channelStatus === 'SUBSCRIBED') onChange(null);
        });
      return () => client.removeChannel(channel);
    },
  };
}

/** Hebrew message for a Supabase auth error. */
export function describeAuthError(error) {
  const code = error?.code ?? '';
  const message = String(error?.message ?? '');
  if (code === 'invalid_credentials' || /invalid login credentials/i.test(message)) return 'אימייל או סיסמה שגויים';
  if (code === 'email_not_confirmed' || /email not confirmed/i.test(message)) return 'צריך לאשר קודם את כתובת המייל - הקישור נשלח לתיבת הדואר';
  if (code === 'user_already_exists' || /already registered/i.test(message)) return 'כבר קיים חשבון עם המייל הזה';
  if (code === 'weak_password' || /password should be/i.test(message)) return 'הסיסמה חלשה מדי - לפחות 6 תווים';
  if (code === 'over_email_send_rate_limit' || /rate limit/i.test(message)) return 'נשלחו יותר מדי בקשות. כדאי לנסות שוב בעוד כמה דקות';
  if (code === 'same_password') return 'הסיסמה החדשה זהה לישנה';
  if (/fetch|network/i.test(message) || error?.name === 'AuthRetryableFetchError') return 'אין חיבור לשרת. כדאי לבדוק את החיבור לאינטרנט';
  return 'משהו השתבש. כדאי לנסות שוב';
}
