// Supabase connection for cloud sync and login.
//
// Production: config.js is generated by .github/workflows/deploy-pages.yml from the repository
// Variables SUPABASE_URL and SUPABASE_ANON_KEY - nothing to do here.
// Local development: copy this file to config.js (git-ignored) and fill in the two values.
// Leave them empty (or have no config.js) to run without an account - data then stays in this browser only.
//
// The anon / publishable key is meant to be public: access is enforced by row-level security
// in the database (supabase/schema.sql), not by keeping this key secret.

export const SUPABASE_URL = '';
export const SUPABASE_ANON_KEY = '';
